[profile.default]
src = "src"
out = "out"
gas_reports = [
    "GHOPaymaster"
]
libs = ["lib"]
gas_reports_ignore = ["test"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 10000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
